name: Update BMKG Data

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-data:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install library
        run: |
          pip install pandas requests openpyxl

      - name: Run get_data.py
        run: python scripts/get_data.py

      - name: Run gabung_data.py
        run: python scripts/gabung_data.py

      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Auto update BMKG data" || echo "No changes"
          git push
